[package]
name = "toto"
version = "1.0.0"
edition = "2021"
rust-version = "1.80"
description = "Toto is a fuzzy finder for your shell tricks 🐾"
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = { version = "1", default-features = false, features = ["std", "unicode-perl"] }
nucleo-matcher = "0.3"
rayon = "1"
anyhow = "1"
shellwords = "1"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
etcetera = "0.10"
unicode-width = "0.2"
libc = "0.2"
ignore = "0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
