mod config;
mod files;
mod item;
mod matcher;
mod parser;
mod picker;
mod runner;
mod usage;

use std::io::{self, BufRead};
use std::path::PathBuf;

use anyhow::Result;
use clap::{Parser as ClapParser, Subcommand};

use crate::config::{load_config, resolve_trick_paths};
use crate::files::find_trick_files;
use crate::item::VariableMap;
use crate::matcher::Scheme;
use crate::parser::{parse_file, ParseResult};
use crate::picker::{ItemSource, PickResult, PickerConfig, TrickEntry, TricksDisplay};

#[derive(ClapParser, Debug)]
#[command(
    name = "toto",
    version,
    about = "Minimal fuzzy finder and interactive trickbook for .trick.md files"
)]
struct Cli {
    /// Colon-separated trick file paths
    #[arg(long)]
    path: Option<String>,

    /// Print selected item instead of executing
    #[arg(long)]
    print: bool,

    /// Pre-fill search query
    #[arg(long)]
    query: Option<String>,

    /// Auto-select best matching snippet
    #[arg(long)]
    best_match: bool,

    /// Filter tags (e.g. "git,!checkout")
    #[arg(long)]
    tag_rules: Option<String>,

    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Print shell integration script for eval
    Init {
        #[arg(value_enum)]
        shell: ShellType,
    },
    /// Show paths and configuration info
    Info {
        #[command(subcommand)]
        what: InfoCommand,
    },
}

#[derive(Subcommand, Debug)]
enum InfoCommand {
    /// Print default config file path
    ConfigPath,
    /// Print default tricks directory path
    TricksPath,
    /// Print a sample config.toml
    SampleConfig,
}

#[derive(clap::ValueEnum, Clone, Debug)]
enum ShellType {
    Bash,
    Zsh,
}

const SAMPLE_CONFIG: &str = r#"# toto configuration
# Place this file at: ~/.config/toto/config.toml

[paths]
# tricks = ["~/.local/share/toto/tricks", "/opt/shared-tricks"]

[shell]
# command = "bash"

[picker]
# preview_height = 7
# height = "full"          # default: "full", "40%", or "20"
# tricks_height = "full"   # override for tricks mode
[keys]
# tricks = "\\C-t"
"#;

/// Parse tag rules like "git,!checkout" into (allowlist, denylist).
fn parse_tag_rules(rules: &str) -> (Vec<String>, Vec<String>) {
    let mut allow = Vec::new();
    let mut deny = Vec::new();
    for tag in rules.split(',').map(|s| s.trim()) {
        if tag.is_empty() {
            continue;
        }
        if let Some(stripped) = tag.strip_prefix('!') {
            deny.push(stripped.to_string());
        } else {
            allow.push(tag.to_string());
        }
    }
    (allow, deny)
}

/// Split a tags string like "git, podman" into individual tag words.
fn split_tags(tags: &str) -> impl Iterator<Item = &str> {
    tags.split(',').map(|s| s.trim()).filter(|s| !s.is_empty())
}

fn apply_tag_filter(items: &[item::Item], allow: &[String], deny: &[String]) -> Vec<usize> {
    items
        .iter()
        .enumerate()
        .filter(|(_, item)| {
            let item_tags: Vec<&str> = split_tags(&item.tags).collect();
            for d in deny {
                if item_tags.iter().any(|t| *t == d.as_str()) {
                    return false;
                }
            }
            if !allow.is_empty() {
                return allow
                    .iter()
                    .any(|a| item_tags.iter().any(|t| *t == a.as_str()));
            }
            true
        })
        .map(|(i, _)| i)
        .collect()
}

fn generate_bash_init(tricks_key: &str) -> String {
    format!(
        r#"# toto shell integration for Bash
# Generated by: toto init bash

# Tricks picker
_toto_tricks() {{
    local output
    output="$(toto --print 2>/dev/tty)"
    if [ -n "$output" ]; then
        READLINE_LINE="$output"
        READLINE_POINT=${{#output}}
    fi
}}

bind -x '"{tricks_key}": _toto_tricks'
"#
    )
}

fn generate_zsh_init(tricks_key: &str) -> String {
    format!(
        r#"# toto shell integration for Zsh
# Generated by: toto init zsh

# Tricks picker
_toto_tricks() {{
    local output
    output="$(toto --print 2>/dev/tty)"
    if [[ -n "$output" ]]; then
        LBUFFER="$output"
        RBUFFER=""
    fi
    zle reset-prompt
}}
zle -N _toto_tricks
bindkey '{tricks_key}' _toto_tricks

"#
    )
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let is_tty = atty_stdin();

    // Info subcommands don't need config
    if let Some(Commands::Info { what }) = &cli.command {
        match what {
            InfoCommand::ConfigPath => {
                if let Some(p) = files::default_config_path() {
                    println!("{}", p.display());
                }
            }
            InfoCommand::TricksPath => {
                if let Some(p) = files::default_tricks_dir() {
                    println!("{}", p.display());
                }
            }
            InfoCommand::SampleConfig => {
                print!("{}", SAMPLE_CONFIG);
            }
        }
        return Ok(());
    }

    // Load config once, pass to all sub-functions
    let config = load_config();

    // Handle subcommands
    match &cli.command {
        Some(Commands::Init { shell }) => {
            let keys = &config.keys;
            match shell {
                ShellType::Bash => print!("{}", generate_bash_init(&keys.tricks)),
                ShellType::Zsh => print!("{}", generate_zsh_init(&keys.tricks)),
            }
            return Ok(());
        }
        Some(Commands::Info { .. }) => unreachable!(), // handled above
        None => {}
    }

    // Pipe mode: stdin is piped, no flags that imply tricks mode
    if !is_tty && cli.path.is_none() && !cli.best_match && !cli.print {
        return run_pipe(&config);
    }

    // Default: tricks mode
    run_tricks(&cli, &config)
}

// -- Pipe mode --

fn run_pipe(config: &config::Config) -> Result<()> {
    let items: Vec<String> = io::stdin().lock().lines().filter_map(|l| l.ok()).collect();

    if items.is_empty() {
        eprintln!("toto: no input");
        std::process::exit(1);
    }

    let height = picker::parse_height(config.picker.height_for("pipe"));

    let picker_config = PickerConfig {
        prompt: "pipe".to_string(),
        scheme: Scheme::Default,
        height,
        initial_query: None,
        edit_enabled: false,
        tricks: None,
    };

    match picker::run(ItemSource::Static(items), &picker_config)? {
        PickResult::Selected(_, item) => {
            println!("{item}");
        }
        PickResult::Cancelled => {
            std::process::exit(130);
        }
        PickResult::Edit { .. } => {} // unreachable in pipe mode (Ctrl-E = end-of-line)
    }

    Ok(())
}

// -- Tricks mode --

fn run_tricks(cli: &Cli, config: &config::Config) -> Result<()> {
    let paths = resolve_trick_paths(cli.path.as_deref(), config);

    if paths.is_empty() {
        eprintln!("No trick paths configured. Use --path, TOTO_PATH, or config.toml");
        std::process::exit(1);
    }

    let history_enabled = config.history.enabled;
    let mut usage = if history_enabled {
        usage::Usage::load()
    } else {
        usage::Usage::default()
    };

    let (allow, deny) = cli
        .tag_rules
        .as_deref()
        .map(parse_tag_rules)
        .unwrap_or_default();

    let mut cache = TrickCache::new();
    let (mut all_items, mut all_variables) = cache.load(&paths)?;
    let height = picker::parse_height(config.picker.height_for("tricks"));

    let mut initial_query = cli.query.clone();

    let selected_idx = if cli.best_match {
        let query = initial_query.as_deref().unwrap_or("");
        let match_texts = build_match_texts(&all_items, &allow, &deny);
        match picker::best_match(&match_texts, query, Scheme::Default) {
            Some(idx) => {
                // idx is into match_texts, need to map back to all_items
                let visible = apply_tag_filter(&all_items, &allow, &deny);
                visible[idx]
            }
            None => {
                eprintln!("No match found.");
                std::process::exit(1);
            }
        }
    } else {
        loop {
            let (entries, match_texts, visible_indices) =
                build_trick_entries(&all_items, &allow, &deny, &usage, history_enabled);

            let picker_config = PickerConfig {
                prompt: "tricks".to_string(),
                scheme: Scheme::Default,
                height,
                initial_query: initial_query.take(),
                edit_enabled: true,
                tricks: Some(TricksDisplay {
                    entries,
                    preview_height: config.picker.preview_height,
                }),
            };

            match picker::run(ItemSource::Static(match_texts), &picker_config)? {
                PickResult::Selected(idx, _) => break visible_indices[idx],
                PickResult::Cancelled => std::process::exit(0),
                PickResult::Edit { index, query, .. } => {
                    let item_idx = visible_indices[index];
                    let item = &all_items[item_idx];
                    launch_editor(item.file.as_deref(), item.line);
                    // Only re-parse files that changed since last load
                    let (new_items, new_vars) = cache.load(&paths)?;
                    all_items = new_items;
                    all_variables = new_vars;
                    initial_query = Some(query);
                }
            }
        }
    };

    let selected = &all_items[selected_idx];

    if history_enabled {
        let usage_key = usage::make_key(&selected.tags, &selected.comment);
        usage.record(&usage_key);
    }

    let shell = &config.shell.command;

    let final_cmd = runner::interpolate(&selected.snippet, &selected.tags, &all_variables, shell)?;

    let final_cmd = match final_cmd {
        Some(cmd) => cmd,
        None => std::process::exit(0),
    };

    let final_cmd = item::snippet_to_display(&final_cmd);

    if cli.print {
        print!("{final_cmd}");
    } else {
        runner::execute(&final_cmd, shell)?;
    }

    Ok(())
}

/// Cache for parsed trick files. Tracks modification times so only changed
/// files are re-parsed on edit-reload cycles.
struct TrickCache {
    /// Per-file cache: path -> (mod_time, items, variables)
    entries:
        std::collections::HashMap<PathBuf, (std::time::SystemTime, Vec<item::Item>, VariableMap)>,
}

impl TrickCache {
    fn new() -> Self {
        Self {
            entries: std::collections::HashMap::new(),
        }
    }

    /// Load/reload tricks. Only re-parses files whose modification time changed.
    fn load(&mut self, paths: &[PathBuf]) -> Result<(Vec<item::Item>, VariableMap)> {
        let trick_files = find_trick_files(paths);
        if trick_files.is_empty() {
            eprintln!("No .trick.md files found in: {:?}", paths);
            std::process::exit(1);
        }

        // Remove entries for files that no longer exist
        let file_set: std::collections::HashSet<&PathBuf> = trick_files.iter().collect();
        self.entries.retain(|k, _| file_set.contains(k));

        // Parse new/modified files, reuse cached ones
        for file in &trick_files {
            let mod_time = std::fs::metadata(file)
                .and_then(|m| m.modified())
                .unwrap_or(std::time::SystemTime::UNIX_EPOCH);

            let needs_parse = match self.entries.get(file) {
                Some((cached_time, _, _)) => *cached_time != mod_time,
                None => true,
            };

            if needs_parse {
                match parse_file(file) {
                    Ok(ParseResult { items, variables }) => {
                        self.entries
                            .insert(file.clone(), (mod_time, items, variables));
                    }
                    Err(e) => {
                        eprintln!("Warning: failed to parse {}: {e}", file.display());
                    }
                }
            }
        }

        // Merge all cached entries in file order
        let mut all_items = Vec::new();
        let mut all_variables = VariableMap::default();
        for file in &trick_files {
            if let Some((_, items, variables)) = self.entries.get(file) {
                all_items.extend(items.iter().cloned());
                all_variables.merge(variables.clone());
            }
        }

        if all_items.is_empty() {
            eprintln!("No trick items found.");
            std::process::exit(1);
        }

        Ok((all_items, all_variables))
    }
}

/// Format the match text for fuzzy searching: "tags comment snippet".
fn format_match_text(tags: &str, comment: &str, snippet_display: &str) -> String {
    format!("{tags} {comment} {snippet_display}")
}

fn build_match_texts(all_items: &[item::Item], allow: &[String], deny: &[String]) -> Vec<String> {
    let visible = apply_tag_filter(all_items, allow, deny);
    visible
        .iter()
        .map(|&i| {
            let item = &all_items[i];
            format_match_text(&item.tags, &item.comment, &item.snippet_display)
        })
        .collect()
}

fn build_trick_entries(
    all_items: &[item::Item],
    allow: &[String],
    deny: &[String],
    usage: &usage::Usage,
    history_enabled: bool,
) -> (Vec<TrickEntry>, Vec<String>, Vec<usize>) {
    let visible_indices = apply_tag_filter(all_items, allow, deny);
    let mut order: Vec<usize> = (0..visible_indices.len()).collect();
    if history_enabled {
        let counts: Vec<u64> = visible_indices
            .iter()
            .map(|&i| {
                let item = &all_items[i];
                usage.get(&usage::make_key(&item.tags, &item.comment))
            })
            .collect();
        order.sort_by(|&a, &b| counts[b].cmp(&counts[a]).then(a.cmp(&b)));
    }
    let mut entries = Vec::with_capacity(order.len());
    let mut match_texts = Vec::with_capacity(order.len());
    let mut sorted_indices = Vec::with_capacity(order.len());

    for &pos in &order {
        let item_idx = visible_indices[pos];
        let item = &all_items[item_idx];
        let snippet_full = item.snippet_display.clone();
        let snippet_preview = snippet_full.lines().next().unwrap_or("").to_string();
        let usage_count = if history_enabled {
            usage.get(&usage::make_key(&item.tags, &item.comment))
        } else {
            0
        };
        match_texts.push(format_match_text(&item.tags, &item.comment, &snippet_full));

        entries.push(TrickEntry {
            tags: item.tags.clone(),
            comment: item.comment.clone(),
            snippet_preview,
            snippet_full,
            detail: item.detail.clone(),
            usage_count,
            file: item.file.clone(),
            source_line: item.line,
        });

        sorted_indices.push(item_idx);
    }

    (entries, match_texts, sorted_indices)
}

fn launch_editor(file: Option<&str>, line: Option<usize>) {
    let Some(file) = file else {
        eprintln!("No source file for this item.");
        return;
    };

    let editor = std::env::var("EDITOR")
        .or_else(|_| std::env::var("VISUAL"))
        .unwrap_or_else(|_| "vi".into());

    let tty_in = match std::fs::File::open("/dev/tty") {
        Ok(f) => f,
        Err(e) => {
            eprintln!("Failed to open /dev/tty for editor: {e}");
            return;
        }
    };
    let tty_out = match std::fs::OpenOptions::new().write(true).open("/dev/tty") {
        Ok(f) => f,
        Err(e) => {
            eprintln!("Failed to open /dev/tty for editor: {e}");
            return;
        }
    };

    let mut cmd = std::process::Command::new(&editor);
    if let Some(n) = line {
        cmd.arg(format!("+{n}"));
    }
    cmd.arg(file);

    match cmd
        .stdin(std::process::Stdio::from(tty_in))
        .stdout(std::process::Stdio::from(tty_out))
        .stderr(std::process::Stdio::inherit())
        .status()
    {
        Ok(status) => {
            if !status.success() {
                eprintln!("Editor exited with: {status}");
            }
        }
        Err(e) => {
            eprintln!("Failed to launch editor '{editor}': {e}");
        }
    }
}

fn atty_stdin() -> bool {
    use std::os::unix::io::AsRawFd;
    let fd = io::stdin().as_raw_fd();
    unsafe { libc::isatty(fd) != 0 }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tag_rules_parsing() {
        let (allow, deny) = parse_tag_rules("git,podman,!checkout");
        assert_eq!(allow, vec!["git", "podman"]);
        assert_eq!(deny, vec!["checkout"]);
    }

    #[test]
    fn tag_rules_empty() {
        let (allow, deny) = parse_tag_rules("");
        assert!(allow.is_empty());
        assert!(deny.is_empty());
    }

    #[test]
    fn tag_filter_deny() {
        let items = vec![
            item::Item {
                tags: "git, checkout".into(),
                comment: "co".into(),
                snippet: "git co".into(),
                ..item::Item::new()
            },
            item::Item {
                tags: "git, push".into(),
                comment: "push".into(),
                snippet: "git push".into(),
                ..item::Item::new()
            },
        ];
        let visible = apply_tag_filter(&items, &[], &["checkout".into()]);
        assert_eq!(visible, vec![1]);
    }

    #[test]
    fn tag_filter_allow() {
        let items = vec![
            item::Item {
                tags: "podman".into(),
                comment: "ps".into(),
                snippet: "podman ps".into(),
                ..item::Item::new()
            },
            item::Item {
                tags: "git".into(),
                comment: "log".into(),
                snippet: "git log".into(),
                ..item::Item::new()
            },
        ];
        let visible = apply_tag_filter(&items, &["podman".into()], &[]);
        assert_eq!(visible, vec![0]);
    }
}
